### ISSUE TITLE
Mod causes Villager's model to not Load

### ISSUE THREAD

**Issue by XModxGodX** [Challat/Waluigi-Moveset#1]
I tried loading the Tingle spirit battle and even if Waluigi's not present Villager appears as an invisible tiny character. When I disabled it through the eshop menu he works normal. Seems to be pretty consistant.

**Comment by Challat** [comment]
I'll check this issue out

**Comment by XModxGodX** [comment]
I THINK I figured it out. If a character starts a battle with a size modification in spirit mode it messes up their size for some reason. It's even worse in the bokoblin fight where all the K Rools die instantly and the last one never spawns leaving you in a stalemate. Guessing your mod messes up how size is calculated for fighter_kind_corps entities which spirit mode uses for the opponents. (maybe classic mode as well)

**Comment by XModxGodX** [comment]
I was able to narrow it down to plugin.nro being the cause of it don't know if that'll help or not but yeah...
